#
# CSC 548: HW1 Problem 3
# Group Info:
#
# aapatel8 Akshit Patel
# kmishra Kushagra Mishra
# pranjan Pritesh Ranjan
#
# Makefile:
#

all: mpi_p3

mpi_p3:
	mpicc -lm -O3 -o mpi_p3 p3.c

clean:
	rm -rf *.dat mpi_p3
